### PR TITLE
Add snap system updater

### PR DESCRIPTION
**Pull request by evitalis**
Moving this port to here per https://github.com/qbit/snap/pull/42

### CODE REVIEW

**Comment by mazocomp** [comment]
@evitalis I'm currently sleepy, so I'll test this port later.

Before I merge this port, I'd like to know the following:
* Why did you set REVISION variable?
* Why did you set PKG_ARCH variable?
* Why you didn't add comment above PERMIT_PACKAGE_CDROM? You should explicitly say which license the ported stuff uses.
* What is the point of DISTNAME, DISTVERS and PKGNAME variables if you already use GH_* variables?
* You don't need to set HOMEPAGE if you use GH_* variables
* Is this port finished? What is left to do if not?
* If this port is finished, why didn't you suggest it at ports@ mailing list?
* If I merge this port, will you maintain it?

**Comment by mazocomp** [comment]
@evitalis And please provide longer description, the following would look much better:
snap is a ksh script designed to upgrade an OpenBSD machine to the latest
snapshot available. Upgrading from release to release is not supported.

**Comment by mazocomp** [comment]
@qbit Can you please provide install script so there won't be need in do-install?

**Comment by ibara** [comment]
Reading over the discussion over on @qbit's repo, I wonder if afterwards, your (aka @evitalis) time is better spent extending snap to upgrade from release (or -stable) to release (or -current), if only to disabuse @qbit from the notion that his software isn't destined for the ports tree :)

**Comment by mazocomp** [comment]
@evitalis I've fixed this port for you, take this as education. But you're not willing to fix and maintain this port, so I won't merge it.

**Comment by qbit** [comment]
@mazocomp thta's a bit heavy handed. For you to say @evitalis is "not willing to fix" seems a bit out of line given the work they have done so far shows the opposite. Especially given the timespan of 14 hours.

Anyway - I have updated the release process to attach tarballs (also signed). Also, there is already a makefile in snap that does an install.

**Comment by qbit** [comment]
@mazocomp I mean the `.include <bsd.prog.mk>` at the end. It imports an install target:

```
qbit@slip[130]:snap[master=]λ doas make install
install -c -o root -g bin -m 555  /home/qbit/dev/snap/snap /usr/local/bin/snap
install -c -o root -g bin -m 444  snap.8 /usr/local/man/man8/snap.8
qbit@slip[0]:snap[master=]λ 
```

**Comment by mazocomp** [comment]
@qbit Argh, apropos(1) doesn't give manual for bsd.prog.mk

**Comment by ibara** [comment]
@evitalis Keep in mind that the two developers in this thread wanted this port and (at least I) wanted you to work on improving snap.

It was the one rando who was showing you animosity.

Don't let the randos get you down.

**Comment by evitalis** [comment]
@ibara I do have that in mind which was why I made the comment about working on snap first, then the port. So I am just pulling the port PR but plan to help work on snap as I am able going forward.

I appreciate you and @qbit helping me improve and talk through stuff.

**Pull request closed without merging**
