### PR TITLE
Add games/warsow and lang/angelscript ports.

### PR DESCRIPTION
**Pull request by mazocomp**
Please do not update AngelScript, Warsow uses deprecated enumerations in AngelScript and I can't patch the game to use replacements (also Warsow is abandonware, but the game is nice and still some people play it: http://livesow.net/#). Warsow itself compiles successfully, but fails to link (I was so close... I don't think I am capable to fix this). Also I didn't make sure lang/angelscript generates static library. Also I wouldn't be able to go this far without help from @Lyberta (she is C++ guru) and my boyfriend @whesun (because I am too stupid to write Linux's sendfile(2) implementation).

### CODE REVIEW

**Comment by mazocomp** [comment]
Thanks to @brynet link-time error is fixed.

**Comment by mazocomp** [comment]
For some reason the game doesn't start (no error messages in output), but at least I managed to install it.

**Comment by ibara** [comment]
If Warsow is abandoned we can assume it never gets any updates, yes?
Could you maybe roll your own tarball with the angelscript code included and build it as a static library that links into the executable? I could imagine people wanting a newer version of angelscript in ports at some point.

**Comment by mazocomp** [comment]
@ibara we might get updates from new developers https://github.com/Warsow/qfusion/

Also AngelScript is already included in Warsow SDK tarball, but I failed to start building it, so I need to better play with CMake.

**Comment by mazocomp** [comment]
AngelScript 2.33.0 is ready to be sent to ports@ :)

**Comment by mazocomp** [comment]
For some reason I can build AngelScript 2.29.2 by using CMake only if I build it outside Warsow, but when I try to build it with Warsow it results in error.

**Comment by mazocomp** [comment]
Ok, now Warsow compiles with AngelScript completely, but still doesn't run :(

**Comment by mazocomp** [comment]
Warsow fails to load ref_gl.so and I don't know why, DGB gives no output on that.

**Comment by mazocomp** [comment]
s/DGB/GDB/

**Comment by mazocomp** [comment]
Any ideas why build broke after I've followed CMake's documentation (last commit)?

**Comment by mazocomp** [comment]
Still thanks to @jbeich I know how binaries and libraries in Warsow are supposed to be named. Now I just need to patch the engine so there won't be a need to use names like libref_gl_openbsd_amd64.so

**Comment by mazocomp** [comment]
Also I don't want to confuse myself, so I'll keep all patches in sync as much as possible with patches I sent to qfusion and Warsow upstreams: https://github.com/Qfusion/qfusion/pull/434

**Comment by mazocomp** [comment]
Right now debugging runtime is more important than fixing file names.

**Comment by mazocomp** [comment]
Yes! I did it! Now Warsow runs at OpenBSD! Now I just need to fix file names and make Warsow look for data files in /usr/local/share/warsow by default.

**Comment by mazocomp** [comment]
And I also need to do something with modules_21.pk3, it fails checksum when trying to connect to any server, but if I include it then Warsow will refuse to use libgame_openbsd_${ARCH}.so and libcgame_openbsd_${ARCH}.so, I have to modify Warsow's source to ignore modules_21.pk3 (so far I played tutorial).

**Comment by mazocomp** [comment]
Thanks to FreeBSD ports I've solved two problems: modules_21.pk3 and looking into right directory for data files. Now I can think about polishing Makefiles and getting rid of _openbsd_${ARCH} suffixes.

**Comment by mazocomp** [comment]
Now you can really play this game online, enjoy it <3

**Comment by mazocomp** [comment]
99% finished, only Makefiles are left to polish.

**Comment by mazocomp** [comment]
Finally it is done.

**Comment by mazocomp** [comment]
All of these are sent to ports@

**Comment by mazocomp** [comment]
I am closing this PR because these are already sent to ports@ and the amount of patches is so big that I am going to fork qfusion and apply all these patches to it, so I'll have less problems keeping them in sync when I'll port Warsow to FreeBSD, NetBSD and DragonFly BSD

**Pull request closed without merging**
