### PR TITLE
jetbrains-clion 2019.2.4

### PR DESCRIPTION
**Pull request by elewarr**
Update for CLion 2019.2.4:
1. a bit more aggresive *.so removal (jbr/ isn't removed, should it?)
1. removed {clang,cmake}/linux directories (left ${INSTALL_DATA_DIR} ${CL}/bin/clang/linux - I assume it was for clangd symlink from clang-tools-extra?)
1. added devel/cmake as dependency
1. building and running simple project from scratch does work (used devel/llvm for that)
1. debugging doesn't work but I can't make devel/lldb cooperate even without CLion (can't run executables in lldb, help!)
1. tar does complain about too long filenames in ./plugins/python/helper/tests

### CODE REVIEW

**Comment by elewarr** [comment]
Actually I don't think CLion port is worth any effort until more is revealed: 
> [...] Clangd-based language engine CLion uses is not a general Clangd build, it’s customized by our team and not upstreamed.
https://twitter.com/clion_ide/status/1185141278159310853?s=20. 

And this feels like a crucial part of the whole IDE.

**Comment by elewarr** [comment]
closing

**Comment by sizeofvoid** [comment]
@elewarr thanks for your effort here. "CLion uses is not a general Clangd build, it’s customized by our team and not upstreamed." Good to know but very sad.

**Comment by elewarr** [comment]
I got in touch with CLion team. They asked for more details. I’ll track it. https://youtrack.jetbrains.com/issue/CPP-17757

**Pull request closed without merging**
