### PR TITLE
add clang patches as posted by brynet@ 

### PR DESCRIPTION
**Pull request by rfht**
https://gist.github.com/brynet/39da2af65331aa9f7e2e51167dc089ee

@ibara please review/comment when you can

### CODE REVIEW

**Comment by rfht** [comment]
@brynet

**Comment by AJenbo** [comment]
@rfht feel free to make a PR for https://github.com/diasurgical/devilutionX with these changes. Clang is already being used for Mac and iOS builds and probably also will be for Android so that shouldn't be a problem in general.

**Comment by brynet** [comment]
@rfht @AJenbo Just to clarify, the clang patches weren't from FreeBSD. These were fixes I made to allow devilutionX to compile on OpenBSD without the -fms-extensions -fms-compatibility, I assumed that FreeBSD's system headers were fixed to support that. I assumed that based on the CMakeList.txt file and __FreeBSD__ checks for Clang in various files, but I guess FreeBSD is still currently using GCC8.

Just wanted to clarify that these patches were not from FreeBSD.

**Comment by brynet** [comment]
By the way @rfht, if at least the CMakeLists.txt changes go in, the patch-3rdParty_StormLib_src_FileStream_cpp` file can also be removed.

I appreciate you handling this, and for @ibara for making the initial WIP port and bringing this very awesome project to our attention. I'm still crossing my fingers for working multiplayer eventually.

**Comment by ibara** [comment]
Let's do it and get it into ports!

**Pull request merged**
